import {StyleSheet} from 'react-native';

export default landingDesign=StyleSheet.create({
    container:{
        height:'100%',
        width:'100%',
        display:'flex',
        alignItems:'center',
        justifyContent:'space-between',
        backgroundColor:'#FFFFFF',
        flexDirection:'column',
    },
    headerBox:{
        width:'100%',
        height:'10%',
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#0000FF',
    },
    headerText:{
        fontSize:22,
        color:'#ffffff'
    },  
    mainBox:{
        width:'95%',
        height:'40%',
        borderColor:'#FFFFFF',
        borderWidth:2,
        display:'flex',
        justifyContent:'space-around',
        alignItems:'center',
        borderRadius:10,
        backgroundColor:'#dddddd',
    },
    footerBox:{
        width:'95%',
        height:'40%',
        borderColor:'#FFFFFF',
        borderWidth:2,
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center'
    },
    internalMainBoxes:{
        width:'90%',
        height:'20%',
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    inputsValues:{
        width:'45%',
        height:40,
        borderColor:'#00000',
        borderBottomWidth:1,
        display:'flex',
        alignItems:'center',
        justifyContent:'center'
    },
    btnsPercents:{
        width:'20%',
        height:'100%',
        backgroundColor:'#0000FF',
        borderRadius:15,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
    },
    amountBtns:{
        width:'15%',
        height:'80%',
        backgroundColor:'#E3E4D3',
        borderRadius:10,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
    },
    footerInformationContainer:{
        width:'100%',
        height:'70%',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'space-around',
        backgroundColor:'#dddddd',
        borderRadius:10,
    },
    footerBoxesInformation:{
        width:'90%',
        height:35,
        display:'flex',
        alignItems:'center',
        justifyContent:'space-between',
        flexDirection:'row'
    },
    btnSendValues:{
        width:'30%',
        marginTop: 20,
        height:35,
        backgroundColor:'#dddddd',
        marginBottom:50,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:5,
    },
    textBtnpercentTax:{
        fontSize:18,
        color:'#ffffff'
    },
    textBtnSendValues:{
        fontSize:20,
        fontWeight:'bold',
    },
    containerBill:{
        height:'100%',
        width:'100%',
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#000000',
        flexDirection:'column',
    },
    paymentBoxes:{
        width:'80%',
        height:40,
        display:'flex',
        alignItems:'center',
        justifyContent:'space-between',
        flexDirection:'row',
        backgroundColor:'#0000FF',
        borderRadius:5,
        paddingLeft:15,
        paddingRight:15,
    }
})